aggregator:
  kafka:
    config:
      kafka:
        bootstrap-servers: localhost:9092
        consumer-group-id: aggregator.user.actions
        topic:
          user-actions-topic: stats.user-actions.v1
          events-similarity-topic: stats.events-similarity.v1