logging:
  level:
    ru.yandex.practicum: debug
    root: info

grpc:
  server:
    port: 0

server:
  port: 0

kafka:
  topic: stats.user-actions.v1
  bootstrap-servers: localhost:9092
  client-id-config: collector-client
  producer-key-serializer: org.apache.kafka.common.serialization.StringSerializer
  producer-value-serializer: ru.practicum.avro.AvroSerializer