grpc:
  server:
    port: 0
  client:
    collector:
      address: 'discovery:///collector'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

collector:
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      user-actions-topic: stats.user-actions.v1