logging:
  level:
    ru.yandex.practicum: debug
    root: info

grpc:
  server:
    port: 9090

server:
  port: 8888

kafka:
  userActionTopic: stats.user-actions.v1
  bootstrapServers: localhost:9092
  clientIdConfig: collector-client
  producerKeySerializer: org.apache.kafka.common.serialization.StringSerializer
  producerValueSerializer: ru.practicum.avro.AvroSerializer
