spring:
  application:
    name: gateway-server
  config:
    import:
      - 'configserver:'
      - 'classpath:eureka-config.yaml'
  cloud:
    config:
      discovery:
        service-id: config-server
        enabled: true
      fail-fast: true
      retry:
        use-random-policy: true
        max-interval: 10000