spring:
  application:
    name: gateway-server
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        service-id: config-server
        enabled: true
      fail-fast: true
      retry:
        use-random-policy: true
        max-interval: 10000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true
    hostname: localhost
    instance-id: "${spring.application.name}:${random.value}"
    leaseRenewalIntervalInSeconds: 10